#AUTH
app:
  auth:
    jwtExpirationMs: 604800000
    redirectUrl: ${FRONT_URL:}/auth/login
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            scope:
              - user:email
              - read:user
          google:
            scope:
              - email
              - profile

#SWAGGER
springdoc:
  api-docs:
    path: /swagger/v3/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html