spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDP_ISSUER}
  jpa:
    properties:
      hibernate:
        id:
          db_structure_naming_strategy: legacy

#SWAGGER
springdoc:
  api-docs:
    path: /swagger/v3/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html

# Actuator
management:
  server:
    port: 8083
  endpoints:
    web:
      exposure:
        include: info,health

#MONITORING
sentry:
  exception-resolver-order: 0
  release: ${VERSION:0.0.0}
  traces-sample-rate: 1.0